server.port=${PORT:8080}

heatmap.data.path=classpath:data/mapa_de_calor.json

spring.datasource.url=jdbc:h2:mem:sebraedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true